### ISSUE TITLE
JShint not found

### ISSUE THREAD

**Issue by BerkeleyTrue** [taras/grunt-deployd#2]
When running tests within the node module

'''
Running "jshint:all" (jshint) task

> > 2 files lint free.

Running "test" task

Running "deployd:dev" (deployd) task

Running "configureProxies:server" (configureProxies) task
Rewrite rule created for: [/^/api/dpd.js/ -> /dpd.js].
Rewrite rule created for: [/^/api/ -> ].
Proxy created for: /api to localhost:7777

Running "connect:server" (connect) task
Started connect web server on localhost:9000.

Running "qunit:all" (qunit) task
Testing http://localhost:9000/tests/index.html >> Running test: http://localhost:9000/tests/index.html

Error loading module node_modules/grunt-contrib-jshint
Error: Cannot find module '/Users/<user>/angular/app/node_modules/grunt-deployd/node_modules/grunt-contrib-jshint'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/<user>/angular/app/node_modules/grunt-deployd/node_modules/deployd/lib/type-loader.js:39:27
    at process._tickDomainCallback (node.js:459:13)
'''

Clearly jshint is there, as it runs in the beginning, but later is run again and cannot be found. I tried this with deployd pulled from the git and from npm.

System:
Osx, node 0.10.25, deployd 0.6.10

**Comment by svenwoldt** [comment]
yes had the same issue try to just kick jshint out of the gruntfile as a quick work around
